//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "commit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub oid: String,
    pub tree: String,
    pub pid: Vec<u8>,
    pub is_head: bool,
    pub repo_path: String,
    pub author: String,
    pub committer: String,
    pub content: String,
    #[sea_orm(column_type = "Timestamp")]
    pub created_at: chrono::NaiveDateTime,
    #[sea_orm(column_type = "Timestamp")]
    pub updated_at: chrono::NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

